[package]
name = "pulsar_engine"
version = "0.1.0"
edition = "2024"

[dependencies]
gpui = { git = "https://github.com/tristanpoland/zed", rev = "c937a2fcddc79d3b4864a12c0ccd5e149adf44a5" }
once_cell = "1.20.3"
rfd = "0.15.2"
